# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 05:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeValue',
        ),
    ]
