# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0002_auto_20160226_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='normal_water',
            field=models.CharField(max_length=50),
        ),
    ]
