# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Reports', '0002_delete_homevalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='homevalue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.IntegerField()),
                ('medhome', models.IntegerField()),
                ('sqfthome', models.IntegerField()),
                ('rent', models.IntegerField()),
            ],
        ),
    ]
