# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0003_homevalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='disaster_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishist_id', models.IntegerField()),
                ('disasterNumber', models.IntegerField()),
                ('ihProgramDeclared', models.IntegerField()),
                ('iaProgramDeclared', models.IntegerField()),
                ('paProgramDeclared', models.IntegerField()),
                ('hmProgramDeclared', models.IntegerField()),
                ('state', models.CharField(max_length=2)),
                ('disasterType', models.CharField(max_length=2)),
                ('incidentType', models.CharField(max_length=15)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='owners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owners_id', models.IntegerField()),
                ('disasterNumber', models.IntegerField()),
                ('state', models.CharField(max_length=2)),
                ('county', models.CharField(max_length=26)),
                ('zipCode', models.IntegerField()),
                ('averageFemaInspectedDamage', models.IntegerField()),
                ('totalDamage', models.IntegerField()),
                ('noFemaInspectedDamage', models.IntegerField()),
                ('FemaInspectedDamageBetween1And10000', models.IntegerField()),
                ('FemaInspectedDamageBetween10001And20000', models.IntegerField()),
                ('FemaInspectedDamageBetweens20001And30000', models.IntegerField()),
                ('FemaInspectedDamageGreaterThan30000', models.IntegerField()),
                ('ApprovedForFemaAssistance', models.IntegerField()),
                ('RepairReplaceAmount', models.IntegerField()),
                ('RentalAmount', models.IntegerField()),
                ('OtherNeedsAmount', models.IntegerField()),
                ('ApprovedBetween1And10000', models.IntegerField()),
                ('ApprovedBetween100001And25000', models.IntegerField()),
                ('ApprovedBetween25001AndMax', models.IntegerField()),
                ('TotalMaxGrants', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='renters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renters_id', models.IntegerField()),
                ('disasterNumber', models.IntegerField()),
                ('state', models.CharField(max_length=2)),
                ('county', models.CharField(max_length=26)),
                ('zipCode', models.IntegerField()),
                ('validRegistrations', models.IntegerField()),
                ('TotalInspectedWithNoDamage', models.IntegerField()),
                ('TotalWithModerateDamage', models.IntegerField()),
                ('TotalWithMajorDamage', models.IntegerField()),
                ('TotalWithSubstantialDamage', models.IntegerField()),
                ('ApprovedForFemaAssistance', models.IntegerField()),
                ('RepairReplaceAmount', models.IntegerField()),
                ('RentalAmount', models.IntegerField()),
                ('OtherNeedsAmount', models.IntegerField()),
                ('ApprovedBetween1And10000', models.IntegerField()),
                ('ApprovedBetween10001And25000', models.IntegerField()),
                ('ApprovedBetween25001AndMax', models.IntegerField()),
                ('TotalMaxGrants', models.IntegerField()),
            ],
        ),
    ]
