# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0004_disaster_history_owners_renters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disaster_history',
            name='incidentType',
            field=models.CharField(max_length=16),
        ),
    ]
