# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0005_auto_20160227_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owners',
            name='zipCode',
            field=models.IntegerField(null=True),
        ),
    ]
