# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0006_auto_20160227_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owners',
            name='OtherNeedsAmount',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
        migrations.AlterField(
            model_name='owners',
            name='RentalAmount',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
        migrations.AlterField(
            model_name='owners',
            name='RepairReplaceAmount',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
        migrations.AlterField(
            model_name='renters',
            name='OtherNeedsAmount',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
        migrations.AlterField(
            model_name='renters',
            name='RentalAmount',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
        migrations.AlterField(
            model_name='renters',
            name='RepairReplaceAmount',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
    ]
