# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0007_auto_20160227_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renters',
            name='zipCode',
            field=models.IntegerField(null=True),
        ),
    ]
