# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0003_auto_20160226_0207'),
        ('Reports', '0008_auto_20160227_0134'),
    ]

    operations = [
    ]
