# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 22:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0009_merge'),
    ]

    operations = [
        migrations.DeleteModel(
            name='disaster_history',
        ),
        migrations.DeleteModel(
            name='homevalue',
        ),
        migrations.DeleteModel(
            name='owners',
        ),
        migrations.DeleteModel(
            name='renters',
        ),
    ]
