# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0009_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='latitude',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='longitude',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=15),
            preserve_default=False,
        ),
    ]
