# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-28 01:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0011_category_formcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formcategory',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='formcategory',
            name='form_id',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='FormCategory',
        ),
    ]
