# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0012_disaster_history_homevalue_owners_renters'),
    ]

    operations = [
        migrations.DeleteModel(
            name='homevalue',
        ),
    ]
