# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0015_delete_owners'),
    ]

    operations = [
        migrations.CreateModel(
            name='owners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owners_id', models.IntegerField()),
                ('disasterNumber', models.IntegerField()),
                ('state', models.CharField(max_length=2)),
                ('county', models.CharField(max_length=26)),
                ('zipCode', models.IntegerField(null=True)),
                ('averageFemaInspectedDamage', models.IntegerField()),
                ('totalDamage', models.IntegerField()),
                ('noFemaInspectedDamage', models.IntegerField()),
                ('FemaInspectedDamageBetween1And10000', models.IntegerField()),
                ('FemaInspectedDamageBetween10001And20000', models.IntegerField()),
                ('FemaInspectedDamageBetweens20001And30000', models.IntegerField()),
                ('FemaInspectedDamageGreaterThan30000', models.IntegerField()),
                ('ApprovedForFemaAssistance', models.IntegerField()),
                ('RepairReplaceAmount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('RentalAmount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('OtherNeedsAmount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('ApprovedBetween1And10000', models.IntegerField()),
                ('ApprovedBetween100001And25000', models.IntegerField()),
                ('ApprovedBetween25001AndMax', models.IntegerField()),
                ('TotalMaxGrants', models.IntegerField()),
            ],
        ),
    ]
