# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-28 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0015_category_formcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='map_label',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
    ]
