# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0016_owners'),
    ]

    operations = [
        migrations.DeleteModel(
            name='renters',
        ),
    ]
