# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0017_delete_renters'),
    ]

    operations = [
        migrations.CreateModel(
            name='renters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renters_id', models.IntegerField()),
                ('disasterNumber', models.IntegerField()),
                ('state', models.CharField(max_length=2)),
                ('county', models.CharField(max_length=26)),
                ('zipCode', models.IntegerField(null=True)),
                ('validRegistrations', models.IntegerField()),
                ('TotalInspectedWithNoDamage', models.IntegerField()),
                ('TotalWithModerateDamage', models.IntegerField()),
                ('TotalWithMajorDamage', models.IntegerField()),
                ('TotalWithSubstantialDamage', models.IntegerField()),
                ('ApprovedForFemaAssistance', models.IntegerField()),
                ('RepairReplaceAmount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('RentalAmount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('OtherNeedsAmount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('ApprovedBetween1And10000', models.IntegerField()),
                ('ApprovedBetween10001And25000', models.IntegerField()),
                ('ApprovedBetween25001AndMax', models.IntegerField()),
                ('TotalMaxGrants', models.IntegerField()),
            ],
        ),
    ]
