# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-03 03:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0013_report'),
        ('Reports', '0020_auto_20160403_0124'),
    ]

    operations = [
    ]
