# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-03 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0024_auto_20160403_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='major20_3',
        ),
        migrations.AddField(
            model_name='report',
            name='estimated_damage',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='report',
            name='fema_disaster_number',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='report',
            name='perDam',
            field=models.IntegerField(default=-1),
        ),
    ]
