# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-04 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0025_auto_20160403_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='estimated_damage',
            field=models.DecimalField(decimal_places=4, default=-1.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='perDam',
            field=models.DecimalField(decimal_places=4, default=-1.0, max_digits=20),
        ),
    ]
